version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/jiahw4ng/shellforge

linters:
  default: standard

  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
